version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: agendatattoo
      POSTGRES_PASSWORD: agendatattoo
      POSTGRES_DB: agendatattoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - database_network

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: ''
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - database_network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  database_network:
